### ISSUE TITLE
Mesonwrap crashing because path not found

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/mesonwrap#149]
Mesonwrap gives me the following error:

```
(venv) lbcscme@LBCNB963:~/mesonwrap> mesonwrap review --pull-request 1 tclap
Traceback (most recent call last):
  File "/home/lbcscme/mesonwrap/venv/bin/mesonwrap", line 33, in <module>
    sys.exit(load_entry_point('mesonwrap==0.2.0', 'console_scripts', 'mesonwrap')())
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/mesonwrap-0.2.0-py3.6.egg/mesonwrap/cli.py", line 28, in __init__
    getattr(self, self.CMD_PREFIX + command)()
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/mesonwrap-0.2.0-py3.6.egg/mesonwrap/cli.py", line 60, in command_review
    reviewtool.main(*self.args())
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/mesonwrap-0.2.0-py3.6.egg/mesonwrap/tools/reviewtool.py", line 386, in main
    review, sha = r.review()
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/mesonwrap-0.2.0-py3.6.egg/mesonwrap/tools/reviewtool.py", line 117, in review
    r = self.review_int(tmpdir)
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/mesonwrap-0.2.0-py3.6.egg/mesonwrap/tools/reviewtool.py", line 127, in review_int
    branch=self._source_branch)) as head_repo:
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/GitPython-3.1.14-py3.6.egg/git/repo/base.py", line 1032, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/GitPython-3.1.14-py3.6.egg/git/repo/base.py", line 980, in _clone
    repo = cls(path, odbt=odbt)
  File "/home/lbcscme/mesonwrap/venv/lib/python3.6/site-packages/GitPython-3.1.14-py3.6.egg/git/repo/base.py", line 130, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /tmp/tmpiij4ip7w/head
```

**Comment by schmidtw** [comment]
This is still a problem in python 3.9.
